sudo: false
language: php
php:
  - '7.2'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - php -v
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyze src --level max
after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

